spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minierp_db?createDatabaseIfNotExist=true
    username: root
    password: 6464
  security:
    user:
      name: admin
      password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true